---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2025/08/10 14:57
---

-- 【用于实现“秒杀资格的判断”的Lua脚本】


-- 1.参数列表
-- 1.1.优惠券id
local voucherId = ARGV[1]
-- 1.2.用户id
local userId = ARGV[2]

-- 2.数据key
-- 2.1.库存key
local stockKey = 'etlpat:flareTraceEpt:seckill:stock:' .. voucherId
-- 2.2.订单key（用于存放下过单的userId集合）
local orderKey = 'etlpat:flareTraceEpt:seckill:order:' .. voucherId

-- 3.脚本业务
-- 3.1.判断库存是否充足 get stockKey
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足,返回1
    return 1
end
-- 3.2.判断用户是否下过单 SISMEMBER orderKey userId
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 存在,说明是重复下单,返回2
    return 2
end
-- 库存充足，且未买过，可以下单
-- 3.3.扣库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
-- 3.4.下单(保存用户id到order集合中) sadd orderKey userId
redis.call('sadd', orderKey, userId)
-- 成功,返回0
return 0